#!/usr/bin/env python3
"""
Flash Boot Image Generator for RV32E SoC

This script generates a hex file for Flash memory initialization
containing a simple boot program that outputs a message to UART.
"""

import sys
from typing import List, Tuple


class RV32EAssembler:
    """Simple assembler for generating RV32E machine code"""

    @staticmethod
    def lui(rd: int, imm: int) -> int:
        """LUI rd, imm - Load Upper Immediate"""
        return ((imm & 0xFFFFF) << 12) | (rd << 7) | 0x37

    @staticmethod
    def addi(rd: int, rs1: int, imm: int) -> int:
        """ADDI rd, rs1, imm - Add Immediate"""
        return ((imm & 0xFFF) << 20) | (rs1 << 15) | (0 << 12) | (rd << 7) | 0x13

    @staticmethod
    def sw(rs2: int, rs1: int, offset: int) -> int:
        """SW rs2, offset(rs1) - Store Word"""
        imm_11_5 = (offset >> 5) & 0x7F
        imm_4_0 = offset & 0x1F
        return (imm_11_5 << 25) | (rs2 << 20) | (rs1 << 15) | (2 << 12) | (imm_4_0 << 7) | 0x23

    @staticmethod
    def jal(rd: int, offset: int) -> int:
        """JAL rd, offset - Jump and Link"""
        # offset is in bytes, encode as per RISC-V spec
        imm_20 = (offset >> 20) & 0x1
        imm_10_1 = (offset >> 1) & 0x3FF
        imm_11 = (offset >> 11) & 0x1
        imm_19_12 = (offset >> 12) & 0xFF
        imm = (imm_20 << 20) | (imm_10_1 << 1) | (imm_11 << 11) | (imm_19_12 << 12)
        return (imm & 0xFFFFF000) | (rd << 7) | 0x6F


def generate_uart_output_program(message: str) -> List[int]:
    """
    Generate RV32E machine code to output a message to UART

    Args:
        message: String to output to UART

    Returns:
        List of 32-bit instructions
    """
    asm = RV32EAssembler()
    program = []

    # Register allocation
    SP = 2   # x2: stack pointer
    A0 = 10  # x10: UART base address
    A1 = 11  # x11: character data

    # Initialize stack pointer: lui sp, 0x80040 (256KB RAM top)
    program.append(asm.lui(SP, 0x80040))

    # Initialize UART base: lui a0, 0x20000 (UART at 0x20000000)
    program.append(asm.lui(A0, 0x20000))

    # Output each character
    for char in message:
        ascii_val = ord(char)
        # Load character: addi a1, zero, ascii
        program.append(asm.addi(A1, 0, ascii_val))
        # Write to UART: sw a1, 0(a0)
        program.append(asm.sw(A1, A0, 0))

    # Infinite loop: jal zero, 0
    program.append(asm.jal(0, 0))

    return program


def generate_hex_file(program: List[int], filename: str, comments: bool = True):
    """
    Generate hex file for Flash memory initialization

    Args:
        program: List of 32-bit instructions
        filename: Output filename
        comments: Include comments in output
    """
    with open(filename, 'w') as f:
        if comments:
            f.write("// RV32E Boot Program\n")
            f.write("// Generated by generate_boot_image.py\n")
            f.write("//\n")
            f.write("// Format: Verilog $readmemh compatible\n")
            f.write("// Address is in 32-bit words\n")
            f.write("//\n\n")

        for addr, inst in enumerate(program):
            f.write(f"@{addr:08X} {inst:08X}\n")

        if comments:
            f.write(f"\n// Total instructions: {len(program)}\n")
            f.write(f"// Program size: {len(program) * 4} bytes\n")


def main():
    """Main function"""
    # Default message
    message = "RT-Thread Boot\n"

    # Parse command line arguments
    if len(sys.argv) > 1:
        message = sys.argv[1]

    print(f"Generating boot program...")
    print(f"Message: {repr(message)}")

    # Generate program
    program = generate_uart_output_program(message)

    print(f"Program size: {len(program)} instructions ({len(program) * 4} bytes)")

    # Generate hex file
    output_file = "flash_boot.hex"
    generate_hex_file(program, output_file, comments=True)

    print(f"Generated: {output_file}")

    # Also generate a binary file for reference
    bin_file = "flash_boot.bin"
    with open(bin_file, 'wb') as f:
        for inst in program:
            # Little-endian byte order
            f.write(inst.to_bytes(4, byteorder='little'))

    print(f"Generated: {bin_file}")

    # Print disassembly
    print("\nDisassembly:")
    print("-" * 60)
    for addr, inst in enumerate(program):
        print(f"0x{addr*4:08X}:  {inst:08X}")
    print("-" * 60)


if __name__ == "__main__":
    main()
